[mypy]
mypy_path = ./src/stubs
disallow_any_explicit = True
disallow_untyped_calls = True
disallow_untyped_defs = True
files = ./src/pages/datasets.py

[mypy-dash.*]
ignore_missing_imports = True

[mypy-stores.*]
ignore_missing_imports = True

[mypy-dataset_import.*]
ignore_missing_imports = True

