[mypy]
disallow_any_explicit = True
disallow_untyped_calls = True
disallow_untyped_defs = True
no_implicit_optional = True
explicit_package_bases = True
mypy_path = ./src
files = ./src/**/*.py

# libraries
#

[mypy-dash.*]
ignore_missing_imports = True

[mypy-dash_bootstrap_components]
ignore_missing_imports = True

[mypy-diskcache]
ignore_missing_imports = True

[mypy-odm_validation]
ignore_missing_imports = True

[mypy-odm_validation.*]
ignore_missing_imports = True

[mypy-orjson]
ignore_missing_imports = True

[mypy-pandas]
ignore_missing_imports = True

[mypy-yaml]
ignore_missing_imports = True
