[mypy]
disallow_any_explicit = True
disallow_untyped_calls = True
disallow_untyped_defs = True
no_implicit_optional = True
explicit_package_bases = True
mypy_path = ./src
files = ./src/**/*.py

[mypy-dash.*]
ignore_missing_imports = True

[mypy-components.sidebar]
ignore_errors = True

[mypy-dataset_import]
ignore_errors = True

[mypy-odm.*]
ignore_errors = True

[mypy-stores]
ignore_errors = True

[mypy-utils]
ignore_errors = True

[mypy-components.modals]
ignore_errors = True

[mypy-components.topbar]
ignore_errors = True

[mypy-components.conf_dialog]
ignore_errors = True

[mypy-components.upload_dialog]
ignore_errors = True

[mypy-pages.home]
ignore_errors = True

[mypy-app]
ignore_errors = True

[mypy-odm_validation]
ignore_missing_imports = True

[mypy-yaml]
ignore_missing_imports = True
