@startuml

!include ../screens/screens.puml

(*) --> [User is on the **New Validation** screen]"
{{
    $new_validation_screen()
}}
" as new_validation_screen

new_validation_screen --> [User clicks the **Customize Validation** \
button]"
{{
    $create_validation_profile_screen()
}}
" as create_validation_profile_screen

create_validation_profile_screen --> [User clicks on the **Create Profile** \
button] new_validation_screen

create_validation_profile_screen --> [User clicks on the **Cancel** button]\
new_validation_screen

@enduml
