@startuml

!include ../screens/screens.puml

(*) --> [User is on the **View Validation Profiles** dialog]"
{{
    $view_validation_profiles_dialog()
}}
" as view_validation_profiles_dialog 

view_validation_profiles_dialog --> [User clicks on the **Create New Profile** button]"
{{
    $create_validation_profile_dialog()
}}
" as create_validation_profile_dialog

create_validation_profile_dialog --> [User clicks on the **Create Profile** \
button] view_validation_profiles_dialog

create_validation_profile_dialog --> [User clicks on the **Cancel** button]\
view_validation_profiles_dialog

@enduml
