@startuml

!include ../screens/screens.puml

(*) --> [User is on the **View Validation Profiles** screen]"
{{
    $view_validation_profiles_screen()
}}
" as view_validation_profiles_screen

view_validation_profiles_screen --> [User clicks on the **Download** button \
and \n the file download has been initiated] view_validation_profiles_screen

@enduml
