# Dataset upload

## Flow

1. user clicks [import-dataset button](#import-dataset-button)
2. [import-dataset modal](#import-dataset-modal) is shown
3. user clicks the [open-file button](#filepicker) and selects a spreadsheet
   file
4. the file is copied to the browser's virtual filesystem, dataset metadata is
   extracted, and the ok button is enabled
5. user clicks the [ok button](#ok-button)
6. version and table-mapping inference is performed, and import is complete

## Components

### Import dataset button

This is the (prev. known as "upload dataset") menu-button that opens up the
[import-dataset modal](#import-dataset-modal).

### Import dataset modal

This is the import screen (prev. known as the "upload screen"), which uses a
(dash bootstrap) modal to prevent the user from interacting with other parts of
the site until the dataset is fully imported or discarded. It has a file dialog
to import files, and ok & cancel buttons to proceed or discard.

#### filepicker
- show file dialog and import selected file:
    - allowed={'csv', 'xlsx'}
    - multiple=false

#### ok button
- finalize import
- hide modal
- transition to dataset configuration, which in turn takes the user to the
  datasets page

#### cancel button
- delete imported file
- hide modal

## Implementation

See [requirements](#requirements) for the reasons behind this implementation.

### Stores

Memory stores are cleared on page reload, while local stores persist across
sessions.

**memory**:
- `dataset-content`: file content of current dataset
- `import-modal-flag`: import-modal visibility toggle
- `imported-dataset`: metadata of last [imported
  spreadsheet](#imported-spreadsheet-type) file

**local**:
- `datasets`: list of [Dataset](#dataset-type)

### Types

#### Imported spreadsheet type

Used to store intermediate spreadsheet metadata on the client-side, before it's
processed into a [Dataset](#dataset-type).

This is not really a type, just a object/dict structure.

```javascript
{
    'path': 'data.xlsx',
    'tables': {
        'samples': {
            'columns': ['sampleID', ...],
        },
        'measures': ...,
    }
}
```

#### Dataset type

Used for persistent storage of processed dataset metadata.

```python
class Dataset:
    """dataset metadata"""
    opfs_path: str
    name: str
    odm_version: str
    tables: Dict[TableName, OdmTableName]
```

### Javascript callbacks

Javascript/client-callbacks are used to perform client-side actions without
actually transferring data to the server, however, they must be written in
Javascript which is quite tedious, so the amount of client-side functionality
should be limited.

The import-button and the import-modal's ok-button's callback are on the
[python side](#python-callbacks).

When importing a dataset, the path from [filepicker](#filepicker) is used to
copy the file to OPFS and extract metadata which is added to
`imported-dataset`.

Selecting a dataset with the (hypothetical) `dataset-selector` component will
populate `dataset-content` with the actual file content, which in turn may be
uploaded to the server through a callback.

**import-modal.filepicker.value**:
- imported-dataset.data =
    - [get_spreadsheet_metadata](#get_spreadsheet_metadata)
        - [get_file_content](#get_file_content)
            - [import_selected_file](#import_selected_file)
- ok-button.disabled = false

**import-modal.cancel-button.n_clicks**:
- call [delete_file](#delete_file)
- reset import-modal-flag

**datasets.data**:
- dataset-selector.options = datasets.data.map(opfs_path)

**dataset-selector.value**:
- dataset-content.data = [get_file_content](#get_file_content)

### Javascript functions

Javascript functions are used with [clientside
callbacks](https://dash.plotly.com/clientside-callbacks).

An external JS module (for the functions below) can be loaded using:

`external_scripts = [{'src': '../static/mycustom.js', 'type': 'module'}]`

The following javascript snippets are only proofs of concept, and lack error
handling, etc.

#### import_selected_file

Copies the selected file from the users local machine to the browser's virtual
filesystem (OPFS), and returns the new path.

[filepicker](#filepicker) is an html input element with `type=file`.

```javascript
async function () {
    let file = filepicker.files[0];
    let opfs_path = file.name // relative to opfs root
    let opfs_root = await navigator.storage.getDirectory()
    let opfs_file = await opfs_root.getFileHandle(opfs_path, {'create': true})
    let writer = await opfs_file.createWritable()
    await writer.write(file)
    await writer.close()
    return opfs_path
}
```

#### get_file_content

Returns the contents of a file stored in OPFS (encoded as base64).

```javascript
async function (opfs_path) {
    let root = await navigator.storage.getDirectory()
    let handle = await root.getFileHandle(opfs_path)
    let file = await handle.getFile()
    let data = await file.arrayBuffer()
    return await encode_base64(data)
}
```

#### get_filenames

Returns a list of stored opfs filenames.

```javascript
async function () {
    let root = await navigator.storage.getDirectory()
    names = []
    for await (const handle of root.values())
        names.push(handle.name)
    return names
}
```

#### delete_file

```javascript
async function delete_file(opfs_path) {
    let root = await navigator.storage.getDirectory()
    await root.removeEntry(opfs_path)
}
```

#### get_spreadsheet_metadata

Returns metadata from spreadsheet file data. Use excel/csv libraries to
extract the metadata.

Returns the structure of `imported-dataset` as shown in [stores](#stores)

```javascript
function get_spreadsheet_metadata(file_content)
```
Removes file from OPFS.

#### encode_base64

Returns the base64 encoding of a blob.

#### decode_base64

Compliments [encode_base64](#encode_base64).

### Python callbacks

**import-button.n_clicks**:
- set import-modal-flag

**import-modal.ok-button.n_clicks**:
- datasets.data +=
  [add_dataset](#add_dataset)(imported-dataset.data[imported-path.data])
- reset import-modal-flag
- transition to dataset configuration

### Python functions

#### add_dataset

`def add_dataset(opfs_path, table_names, column_names) -> Dataset`

Returns a dataset (metadata) object from the metadata provided, including
auto-detected values for ODM version and table mapping.

auto-detects:
- file type from filename extension
- ODM version and table mapping from table/column names

## Requirements

### Persistence

Imported datasets must be persisted between browsing sessions. We can't
require the user to re-select/import/configure the datasets every time they
close the browser.

### Privacy

Datasets must not be persisted on the server for privacy reasons. This also has
the added benefit of not requiring server storage space. Datasets must,
however, be stored somewhere accessible to the application.

- problems:
    - obviously can't use server file system
    - can't use server /tmp since it may not be mounted in memory, and even
      if it is in memory it won't be persistent for the user if the server
      restarts
    - dash is stateless, so we can't use server-side application state, and it
      wouldn't persist through server restart anyway
    - we don't want to use some complex server storage solution, so
      server-side db is out of the question
    - can't use client filesystem since it requires to ask the user to pick the
      file every time (with the file dialog)
    - dcc.Store is client side (!), however:
        - dcc.Store(memory/session) is not persistent
        - dcc.Store(local) can only hold 5-10 MB
- solution:
    - use [OPFS](https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API#origin_private_file_system).
      The user will only be asked once to pick the file, after which it will be
      stored in the browser's virtual filesystem for future access.
        - examples:
            - https://stackoverflow.com/a/71581910
            - https://webkit.org/blog/12257/the-file-system-access-api-with-origin-private-file-system/
    - upload dataset on demand during validation
