---
title: Technical Specification
format:
  html:
    toc: true
---

# Features

## Dataset upload

Pages required:

- [Home page](#home-page)

Stores required:

- [Uploaded file](#uploaded-file-store)
- [Datasets](#dataset-store)
- [Replace_on_dup](#replace-on-dup-store)

### Importing a dataset

**1. Extract sheet names and data from file**

Sheets/data should be loaded into a dict with sheet-names as keys and table
data as values. A CSV file should be seen as a workbook with a single sheet,
where the sheet name is the filename.

The pandas library can be used to read CSV and Excel files, however, the
resulting DataFrame must be converted to a list of dicts/records before storing
it in the [Dataset](#dataset), since Dash doesn't support serialization of classes.

**2. Infer ODM version from sheet names**

For each ODM version (from latest version to earliest), and for each ODM table,
see if there's a [match](#matching-algorithm). If a sheet matches, the current
version is returned and we're done. If no match is found, default to the latest
ODM version.

New versions have different table names from older versions. if both old
and new table names are found, then we want to pick the latest version.
One reason to prefer the latest is that a user may have old data from
a previous version in the same spreadsheet, and they would want to
use/validate the new data.

One potential issue is that ODM v1 and v1.1 have the same table names, which
means that v1.1 always will be picked over v1, however, that's acceptable and
preferred in any case.

**3. Map tables**

The mapping from sheet names to ODM table names should be inferred from the
sheet names and ODM version.

Start with the set of ODM table names for the inferred version in step 2. For
each sheet name, first assign an empty string to each sheet, then see if
it [matches](#matching-algorithm) with one of the ODM tables names for the
inferred ODM  version, and if so, assign the mapping from sheet to table and
remove table from the set of tables.

Each sheet mapping is initialized to an empty string to keep a record of all
sheets even if some don't match, so that they can be presented to the user as
sheets with unknown tables. This is currently the only place we're storing the
dataset sheet names, so we don't want to lose any information.

The same matching algorithm is used here to be consistent with
inference of the data version.

Each table is only matched at most once so that no more than one sheet maps to
each table. We do not support validating multiple sheets representing the same
table, and it's more likely to be a user error, so it's better to ignore any
extra matches.

This feature is handled by the [dataset_import](#dataset_import) module.

### Matching algorithm

The following algorithm is used to see if a sheet name matches an ODM table
name.

1. Find an ODM table which is exactly the same as the sheet name. If found then
map the sheet to the matched table.
2. If no exact match is found, find an ODM table where the sheet name ends with
a space plus the table name. For eg., if a sheet name is `1 - Measures` then
an ODM table name called `Measures` would result in a match. This was done
due to the way MECP encodes their sheet names which is
`<number> - <table_name>`.

A separator/space has to be included in the match to avoid the edge case where
two different table names have the same ending. Ex: SiteMeasure and WWMeasure.

## Dataset configuration

Screens required:

- [Dataset page](#dataset-page): The user is able to configure the dataset
from this page by clicking the **Configure Dataset** button.
- [Configure dataset dialog](#configure-dataset-dialog)
- Any page with the [Top bar menu](#top-bar-menu): The user is able to
configure a newly uploaded dataset whose flow is initiated by clicking the
**Upload Dataset** button in the top menu bar.

Stores required:

- [conf-dialog-flag](#dialog-flag-stores)
- [dataset-conf-form](#dataset-conf-form-store)
- [dataset-id](#dataset-id-store)
- [datasets](#dataset-store)

Dataset configuration consists of four steps:

**1. Selecting a dataset**

A dataset can be selected by either uploading a new dataset, which selects it
implicitly, or explicitly selecting a dataset from the datasets dropdown in the
top bar menu.

**2. Opening the configuration dialog**

The dataset configuration dialog should be automatically opened after uploading
a dataset, to make sure that the user is informed of the inferred default
values and given the chance to correct them.

The dialog should also be available from the dataset-menu/sidebar on the
page for the selected dataset.

**3. Selecting new values, if any**

The configuration dialog shows the current ODM version and its mapped tables.
Initial values should be inferred from the data, and the user should be able to
re-configure it at any time.

**4. Confirming the change, or canceling**

Changes should only be saved when the user confirms them, and discarded
otherwise, however, initial values may be kept even when canceling the initial
configuration.

After configuration, the user should be taken to the dataset page, where the
updated configuration is reflected in the upload report.

## Dataset validation

Pages required:

- [Dataset](#dataset-page)
- [Validation](#validation-page)

Dialogs required:

- [Validation](#validation-dialog)
- [Validation progress](#validation-progress-dialog)

Stores required:

- [Cancel operation](#cancel-operation-store)
- [Dataset id](#dataset-id-store)
- [Datasets](#dataset-store)
- [Progress dialog flag](#dialog-flag-stores)
- [Validation dialog flag](#dialog-flag-stores)
- [Validation setup](#validation-setup-store)
- [Validation trigger](#validation-trigger-store)
- [Validations](#validation-store)

Dataset validation is performed by clicking the
validate dataset button in the [sidebar](#sidebar) of a
[dataset page](#dataset-page), which opens up the
[validation dialog](#validation-dialog) where the new validation can be setup
and run.

The validation dialog is initialized with a
[generated validation name](#validation-name-generation), which can be changed
by the user. It must be unique per dataset.

The validation profile used for the validation can be chosen from a list. The
list includes any profile added by the user, as well as the default ODM
profile.

Starting the validation switches over to the
[validation-progress dialog](#validation-progress-dialog), which calls
`validate_data` (or its extended version) from the odm validation library. This
is a blocking call that may take a long time to complete, but we can get the
current progress by passing in a python-callback argument. In order to update
the [validation progress dialog](#validation-progress-dialog) with the progress
returned from the `validate_data` call, we need to use a
[Dash background callback](https://dash.plotly.com/background-callbacks), which
in turn requires a "background callback manager" for storing the intermediate
state. An in-memory manager (using Redis) is the recommended choice for
production use, but we'll stick with disk storage temporarily, for simplicity.

The resulting validation report is serialized as json and stored in the
[validation store](#validation-store). Serialization is required due to the
validation report being a class and containing class types, which cannot be
stored in a Plotly store.

Finally, after completing the validation, a new
[validation page](#validation-page) with the validation summary & report will
be created.

### Validation name generation

The algorithm for generating new validation names is as follows:

1. Set the next validation name to be "Validation `n`", where `n` is the
   previous validation count plus one.
2. If the dataset already has a validation with this (case insensitive) name,
   then add one to `n` and check again until it's unique.

## [Exit Confirmation](../tool-spec/tool-spec.qmd#exit-confirmation)

This is implemented using
[Javascript](https://stackoverflow.com/questions/821011/prevent-a-webpage-from-navigating-away-using-javascript).
The code for this is in `src/assets/scripts.js`.

# App

This is the root level of the application, holding application-wide components.

Components:

- Url (dcc.Location)
- [Top bar menu](#top-bar-menu)
- [Page content](#pages)
- [Dialogs](#dialogs)
- [Stores](#stores)

# Pages

## Home page

Path: `/`

The home page is shown to the user when they open the tool. It features a
piece of welcome text, introducing the user to the site and guiding them to the
various functionalities.

Components:

- Welcome text

## Dataset page

Path: `/datasets/<dataset_id>`

The dataset page shows the upload report for the selected dataset, as well as
buttons for configuration and validation in the sidebar.

The upload report doubles as the page content, and is dynamically generated
from the dataset.

Components:

- [Sidebar](#sidebar)
- Dataset page header
- Dataset name
- Upload time
- ODM version
- ODM table count
- ODM tables:
    - Sheet name
    - ODM table name
    - Column count
    - Row count
    - ODM column names
    - Ignored column names
- Ignored sheet count
- Ignored sheet names

## Validation page

Path: `/validations/<dataset_id>/<validation_name>`

This page shows the currently selected dataset validation. It holds the summary
report, as well as access to the full report.

Ideally the URL for the validation page would be nested within the URL for the
dataset page like `/datasets/<dataset_id>/validations/<validation_name>`,
however Dash does not support nested pages, i.e., where a page can be nested
within another page.

Components:

- [Sidebar](#sidebar)
- Validation page header
- Dataset name
- Validation name
- Validation summary
- Validation report download button

# Dialogs

Dialogs are implemented using the [Modal](#modal) component.

## Upload dataset dialog

The upload dialog & co. let the user upload a dataset from a spreadsheet file.

The upload dialog is the main dialog, which performs the actual upload. The
import dialog performs the import and shows progress. It is decoupled from the
upload dialog to enable intermediate actions. One such action is detection and
resolution of uploading a dataset with an existing name, which shows the
duplicate dialog that lets the user decide if they want to update or replace
the dataset. A confirmation dialog is shown if the user chooses to replace the
dataset.

Components:

- upload dialog (modal):
    - file uploader ([dcc.Upload](https://dash.plotly.com/dash-core-components/upload))
    - status text
    - ok button
    - cancel button
- duplicate dialog (modal):
    - explanation text
    - dataset name
    - update button
    - replace button
- confirm replace dialog (dcc.ConfirmDialog)
- import dialog (modal):
    - status text
    - progress bar

Behaviors:

1. When the [upload-dialog-flag](#dialog-flag-stores) changes:
    - The upload dialog should open/close
    - The ok button should be disabled, and status and uploader content cleared
2. A file can be uploaded by either clicking the file-uploader or dragging a
   file onto it. Only one file can be uploaded at a time, and the allowed
   formats are CSV and XLSX.
3. When the upload completes:
    - The file should be stored in the [uploaded-file](#uploaded-file-store) store
    - The upload dialog status text should change to show the uploaded filename
    - The ok button should be enabled
4. When the cancel button is pressed, it should simply close the upload dialog,
   ignoring any uploaded file.
5. When the ok button is pressed, it should:
    1. Close the upload dialog
    2. If duplicate, then open the duplicate dialog, otherwise open the import
       dialog (and initialize its status text to the dataset id)
6. When the duplicate dialog is opened, it should:
    1. Initialize its dataset id text from the uploaded file name
7. When a duplicate resolution is chosen (update/replace), it should:
    1. Close the duplicate dialog
    2. Set [replace-on-dup](#replace-on-dup-store) accordingly
    3. If replace is chosen, then open the replace confirmation dialog,
       otherwise open the import dialog (and initialize its status text to the
       dataset id)
8. When the replacement is confirmed, then it should open the import dialog,
   otherwise (when canceled) it should simply end the flow.
9. When the import dialog is opened, it should:
    1. If it's a duplicate and replace-on-dup is true, then clear any previous
       validations for this dataset.
    2. Construct a Dataset as follows:
        - **filename**: Set from the uploaded file name.
        - **odm_version**: Set from the ODM version inferred while matching table
          names.
        - **table_mapping**: Set to the inferred mapping between sheet names and ODM
          table names. In the case of CSV files, the filename is used as the sheet
          name. Inference is done by seeing if the sheet name matches the a
          hardcoded list of valid ODM table names for any version of the ODM, which
          in turn implies the ODM version. If no match is found it will default to
          the latest version.
        - **tables**: Set to the extracted data of each sheet with a corresponding
          valid ODM table.
    3. Add/update the dataset to/in the [datasets](#dataset-store) store.
    4. If it's not a re-upload, then open the
       [configure dataset dialog](#configure-dataset-dialog).

## Configure dataset dialog

This is the dataset configuration screen. It uses a modal to force the user
through the configuration process after uploading a new dataset. It is used to
configure the odm-version and table-mapping of the dataset, and consists of
pre-populated dropdowns for all settings, together with ok & cancel buttons.

Components:

- modal:
    - filename text
    - odm version text
    - list of dropdowns, mapping sheets to tables
    - ok button
    - cancel button

Behaviors:

1. When the cancel button is clicked:
    - The [conf-dialog-flag](#dialog-flag-stores) should be unset
2. When the [conf-dialog-flag](#dialog-flag-stores) changes:
    - The dialog should open/close
3. When the [conf-dialog-flag](#dialog-flag-stores) is true:
    - The filename and version should be set from the selected dataset
    - Form errors should be reset
4. When the version changes:
    - The table mapping should be re-inferred from the dataset with the new
      version, and the [dataset-conf-form](#dataset-conf-form-store) store should be
      updated to reflect it.
    - The list items for the ODM table dropdowns should be re-generated to have
      the tables for the selected version.
5. When a sheet-table mapping changes:
    - Update the [dataset-conf-form](#dataset-conf-form-store) store with the
      new mapping.
6. When the ok button is clicked:
    - Read the mapping from the [dataset-conf-form](#dataset-conf-form-store)
      store.
    - An error message should be shown if the mapping has duplicate tables
    - The following should happen if the config is valid:
        - Close dialog
        - Update the current dataset with the new config values
        - Go to the page for the current dataset

## Validation dialog

This dialog sets up a new validation to run. The user can specify the
validation name and profile before starting the validation.

**Components**

- modal:
    - validation name textbox
    - validation profile dropdown
    - profile rule list
    - customize profile button
    - start button
    - cancel button

**Behaviors**

1. When the cancel button is clicked:
    - the [validation-dialog-flag](#dialog-flag-stores) should be unset
2. When validation-dialog-flag changes:
    - if false: the dialog should close
    - if true: the dialog should be initialized:
        - a new validation name (unqiue to the dataset) should be generated
        - the rule list should be populated from the selected profile
3. When the start button is clicked:
    - if the validation name isn't unique:
        - show an error
    - else:
        - the validation-dialog-flag should be unset
        - the [progress-dialog-flag](#dialog-flag-stores) should be set
        - the [validation setup store](#validation-setup-store) should be
          initialized with the chosen name and profile
4. TODO: When the customize button is clicked

## Validation progress dialog

This dialog shows the validation progress as well as a minimal result summary.
It also has a button to cancel the validation.

**Components**

- modal:
    - confirm cancel dialog (dcc.ConfirmDialog)
    - dataset name
    - table name
    - progress bar
    - result text

**Behaviors**

1. when [progress-dialog-flag](#dialog-flag-stores) changes:
    - if false, the dialog should close
    - if true, the dialog should open, as well as:
        - reset dialog components
        - set database name from dataset_id store
        - set validation-trigger store
2. when [validation-trigger](#validation-trigger-store) is true:
    - validation of the current dataset should be performed
    1. when validation progress changes:
        - the table name and progress bar should be updated
    2. when the [cancel-operation store](#cancel-operation-store) changes:
        - the validation should be canceled
        - the progress bar should be hidden
        - the cancel button should be disabled
        - the close button should be enabled
    3. when validation completes:
        - the result text should say the validation completed, as well as the
          number of errors and warnings
        - the cancel button should be disabled
        - the close button should be enabled
3. when the cancel button is clicked:
    - the [confirm-cancel-dialog](#dialog-flag-stores) should be shown
4. when the confirm-cancel-dialog's submit button is clicked:
    - the cancel-operation store should be set
    - the current table name should be reset
    - the validation result text should say the validation was canceled
5. when the close button is clicked:
    - the progress-dialog-flag should be reset
    - if the validation wasn't canceled:
        - the url pathname should be set to the validation page for this
          validation

**Issues**

- Showing a confirmation dialog when cancelling the validation doesn't
  necessarily pause the validation while the user is making their final
  decision. The validation may therefore complete after the cancel button is
  clicked, before the cancellation is confirmed. It looks like we have limited
  control over this, and that we just have to make the best out of it.

## View validation profiles dialog

TODO

# UI Components

This section will go through all the UI components used by the different
screens in the tool. Each sub-section contains the details for a UI component
which includes the following:

- A brief description.
- Its behavior which mainly goes over how the user is allowed to interact with
  it.
- Its API which describes how another component can use it.

## Modal

This is the basis for all dialog windows. It prevents the user from interacting
with the rest of the application while a dialog is open. It's using
[dbc.Modal](https://dash-bootstrap-components.opensource.faculty.ai/docs/components/modal/).

Behaviors:

1. It should be initialized to a closed state, and only be opened/closed using
   [dialog flags](#dialog-flag-stores).
2. Clicking outside the modal should close it.
3. Pressing the escape key should close it, unless overridden.

A modal can be created by calling `init_modal` from the components module. It
has the following parameters:

- id: the html-id string of the modal
- title: the title string shown in the header of the modal
- body: a list of child components
- buttons: a list of buttons shown in the footer of the modal
- escape: a bool deciding if the escape key can be used to close the modal

## Top bar menu

This is the main-menu bar at the top of every page.

Menu items:

- Upload dataset
- Datasets: *list of datasets*
- View validation profiles
- Tutorials

Behaviors:

1. The bar should be fixed to the top of the screen. Even if the user
   scrolls, the position of the bar should not change.
2. When the user clicks on the **Upload Dataset** button, the
   [Upload dataset dialog](#upload-dataset-dialog) should be opened.
3. When the user clicks on the **Datasets** button, a dropdown should
   be opened that lists all the datasets that the user has uploaded.
   The dropdown should be closed when the user clicks on any part of
   the app again:
    - Each dataset should be presented to the user using its file
      name.
    - When the user uploads a new dataset, the datasets dropdown list should be updated.
    - When the user clicks on a dataset, it should be selected, and
      the user taken to the [Dataset page](#dataset-page). The dropdown
      should be closed.
    - When the user has not uploaded any datasets, the dropdown should
      only have one item that says **No Datasets Uploaded**.
4. When the user clicks on the **View Validation Profiles** button, the
   [View validation profiles dialog](#view-validation-profiles-dialog) should
   be opened.
5. The **Tutorials** button can be disabled for now.

## Sidebar

The sidebar is shown on pages with a dataset-context, and provides buttons for
configuring and validating the selected dataset, as well as listing previous
validations.

Components:

- Configure dataset button
- Validate dataset button
- List of links to previous validations

Behaviors:

1. The bar should be fixed to the left side of the screen. Even if the user
   scrolls, the content of the bar should stay in place.
2. When the user clicks on the **Configure dataset** button, the
   [Configure dataset dialog](#configure-dataset-dialog) should be opened.
3. When the user clicks the **Validate dataset** button, the
   [Validate dataset dialog](#validate-dataset-dialog) should be opened, using
   the respective [dialog flag store](#dialog-flag-stores).
4. When the [validation store](#validation-store) changes, the list of
   validation links should be (re)generated.

# Stores

This section includes the different stores where the app will persist data.
Each sub-section goes over the details of each store and the data stored within
it.

## Memory stores

All the data in this store type is stored in browser memory. The data is
transient, meaning that the data is lost when the user reloads/closes the tool.

### Dialog flag stores

All flags are currently used as signals for showing and hiding dialogs.
There is one flag per dialog, and they are all of type bool. True means open,
while False means closed.

Some flags (currently only the conf-dialog flag) may hold additional values as
well, making their type an integer rather than a boolean. The reason for this
is to add additional state. In the case of the conf-dialog flag, the additional
state needed is to know which origin the dialog was opened from, which makes it
have multiple true/positive values.

The reason for having signals/flags is to uncouple components from each other,
so that they don't directly reference each other. This prevents complicated
dependencies and cycles.

The flags are:

- conf-dialog-flag, for the
  [configure dataset dialog](#configure-dataset-dialog)
- progress-dialog-flag, for the
  [validation progress dialog](#validation-progress-dialog)
- upload-dialog-flag, for the
  [upload dataset dialog](#upload-dataset-dialog)
- validation-dialog-flag, for the
  [validation dialog](#validation-dialog)

### Uploaded file store

Type: {'filename': str, 'contents': str}

`contents` is base64 encoded.

This store is used by the [upload dataset dialog](#upload-dataset-dialog) to
cache the uploaded file before it's accepted and used in the construction of a
Dataset. To select a dataset in the
[upload dataset dialog](#upload-dataset-dialog) the user has to 1. Choose a dataset by using
the browser's file chooser or dragging and dropping a file into the dialog; and
2. Confirm their choice by clicking the ok button. To avoid wasting computing
time, we want to parse the chosen file into a [`Dataset`](#dataset) only when
they have confirmed their selection, since they can always change their chosen
file. Instead, we store the contents of the chosen file as its given to us by
[Plotly](https://dash.plotly.com/dash-core-components/upload#displaying-uploaded-spreadsheet-contents)
in this store, and parse it into a [`Dataset`](#dataset) only when the user has
confirmed their selection. It also helps in decoupling the upload from the rest
of the application.

### Dataset id store

Type: `str`

This store keeps track of the currently selected dataset. It should be set to
the dataset selected in the dataset-dropdown, as well as a newly uploaded
dataset which gets auto-selected once the upload is complete. The dataset id is
simply its filename, which is unique as the user cannot upload files with the
same name twice.

### Dataset store

Type: `Dict[Filename, Dataset]`

This contains all the datasets that the user has uploaded to the tool. Using a
dictionary over an array of datasets has the following advantages:

1. Datasets are accessed by their filename for quick and easy lookup; and
2. It allows more granular access to individual datasets using the
[Dash Patch Class](https://dash.plotly.com/partial-properties). This should make
the callbacks run faster and with less memory since they would only access the
dataset they need. With an array, each callback would need to
first find the dataset they have to operate over, which requires passing in the
entire datasets array into it.

The fact that users cannot edit a dataset in the tool forces them to update it
in their local file system after validation. After making the required changes
to the dataset, they will need to re-upload it to the tool if they wish to
validate it again. This upload, validate, fix, re-upload cycle means that there
is no need to permanently store a dataset in the OPFS store, since it will
always be out of sync with the version on the user’s local file system.

### Replace on dup store

Type: `bool`

This is an intermediate value indicating if the uploaded dataset should be
updated or replaced when it already exists.

It's needed because it's set and used in two different dialogs (duplicate and
import).

### Dataset conf form store

Type: `Dict[SheetName, TableName]`

This store is used to keep track of the changes made during dataset
configuration using the [configuration dialog](#configure-dataset-dialog),
specifically the dataset table mapping. Every table selection has to be
recorded here before the user confirms the changes. After confirmation it's
saved to the current dataset.

The reasons for using this intermediate store is:

- Difficulty of querying the final state of a set of dynamic dropdowns.
- Being able to wait with commiting changes until confirmed by the user.

### Cancel operation store

Type: `bool`

Needed as an intermediate signal for performing additional actions when
canceling the validation, since the dash background callback doesn't have its
own callback for it.

It's also used to know if a redirect to a new validation summary page should
occur or not, after validation.

### Validation setup store

Type: [`ValidationSetup`](#validation-setup)

Used to store config between validation setup and progress.
'id' since it's not unique across the app, only per dataset.

### Validation trigger store

Type: `Any | bool`

Used to trigger a new validation to start from the validation dialog. This
intermediate signal is required because we need to initialize parts of the
validation-progress dialog before starting the (blocking) validation process.

The type is not significant, but `True` is used, as with the
[cancel operation store](#cancel-operation-store).

### Validation store

Type: `Dict[DatasetId, Dict[ValidationName, Validation]]`

This is the collection of [Validations](#validation).

# Modules

This section provides documentation on the different non-UI modules that are
part of the project.

## odm

This module has ODM definitions and functions.

We may consider moving some or all of this to the odm-validation package in the
future, to avoid duplicate definitions.

### API

- TableName: str
- Version: enum
- get_table_names(Version) -> List[TableName]

### ODM version

The ODM versions can be hardcoded as an enum. Old versions won't be removed and
new ones may be appended to the enum with no issues.

See [Version (ODM)](#version-odm) for current version values.

### ODM table names

A set of valid ODM table names for each ODM version is needed when mapping
sheet names to table names during dataset configuration. They should be
extracted from the odm-validation library's validation-schemas, and cached as a
static asset to improve performance. The cache has to live in the file system
since Dash is stateless.

A simple text file is used for caching, with the version being the file name,
and with one table name per line.

Example file `/tmp/v2.0.0.txt`:

```
addresses
measures
samples
```

**When not cached**:

1. load schemas from odm validation lib:
    1. import odm_validation module
    2. scan the module's asset dir for schema files
2. extract version and table names from each schema
3. construct a dictionary that maps each version to its table names
4. set private module constant `_TABLE_NAMES` to the resulting dict
5. save/cache to tmp dir, one file per schema

**When cached**:

1. scan cache dir for odm table files
2. load each file, using its filename as the version, and reading each line as
   a table name
3. construct a dictionary that maps each version to its table names
4. set `_TABLE_NAMES` to the resulting dict


## dataset_import

This module is responsible for the creation of a [Dataset](#dataset) once the
user has uploaded their dataset file and completed its configuration. It has
the following public API:

* **import_dataset**: The function used for the [dataset](#dataset) creation.
* **Dataset**: The [dataset](#dataset) class.

# Types

This section goes over the structure of the different data that the tool will
store.

Common aliases:
```python
OdmTableName = str
FieldName = str
FieldValue = str
TableRow = Dict[FieldName, FieldValue]
TableData = List[TableRow]
SheetName = str
```

## Version (ODM)

Type: enum

Fields:

- v1_0_0 = 'v1.0.0'
- v1_1_0 = 'v1.1.0'
- v2_0_0 = 'v2.0.0'

The enum keys use underscores in place of dots, due to Python naming requirements. The values represent the correctly formatted version.

Instances of this type can't be used directly in a dcc.Store due to it being a
class/enum, so it's string values should be used instead.

## Dataset

Type: class

Fields:

- `filename: str`

  Used as the datasets unique id. It is shown in the datasets-dropdown in the
  [Top bar menu](#top-bar-menu), and in any screen that is interacting with it.

- `odm_version: str`

  Detected from the dataset or specified by the user. Required for knowing
  which ODM version to validate against. It must have one of the values from
  [OdmVersion](#odmversion).

- `table_mapping: Dict[SheetName, OdmTableName]`

  Maps table/sheet names to valid ODM table names. This is the same for CSV and
  Excel files. CSV files have one sheet with the same name as the file.

  Empty strings are used as default table names, meaning that a sheet mapped to
  an empty string is a sheet without a table mapping.

- `tables: Dict[OdmTableName, TableData]`

  Holds the actual data for each table/sheet.

## Validation

Type: `class of TypedDict`

Fields:

- `name: str`

  Validation name.

- `summary: str`

  Validation summary, encoded as json.

- `report: str`

  Validation report, encoded as json.

## ValidationSetup

This class holds all values needed to perform a validation. Validation names
are not unique by themselves, so their parent dataset_id is also needed to
indentify it.

Type: `class of TypedDict`

Fields:

- `dataset_id: str`
- `validation_name: str`
- `profile_id: str`
