# Validation report

## Components

### Download report button

Also known as the "view validation report" button.

### Report modal

This will be a rather large modal, possibly fullscreen, where the entire
validation report is shown, as well as the download selection.

#### Data table

The data table component (dcc.DataTable) shows the entire validation report as
a set of columns and rows.

The columns are:
- error table name
- error column name
- error row number
- error level (error, warning)
- error id (rule id)
- error message

It should be sorted in the same order as the columns above by default, and the
user should be able to sort by a specific column as well. It may also be
beneficial to have an option to hide warnings, etc.

#### Download selection

This screen lets the user download the selected validation report in the format
and with the error-level they choose.

The UI spec suggests having the error-level options "full, errors, warnings",
but it'll be easier to use the same convention as the validation library uses,
which is to include either just errors or both errors and warnings. I don't
think users would want to see just warnings while ignoring the more serious
errors.

- format dropdown:
    - values: csv, yaml, json
- error-level dropdown:
    - decides the error-level
    - values: "warnings, errors" OR "all, errors only"
- download button:
    - initiates the download
- downloader (dcc.Download):
    - handles the actual file saving/download

## Implementation

### Stores

**memory**:
- `report-content: str`
- `report-download-modal-flag: bool`
- `selected-report-path: str`

### Callbacks

The report content has to be loaded into memory on the client-side before the
modal flag is set, so that the download-btn has content to process.

**download-report-btn.n_clicks (clientside)**:
- load `selected-report-path`'s file content into `report-content` from OPFS
  storage
- set report-download-modal-flag

**report-download-modal-flag.data**:
- set report-download-modal.is_shown
- populate data table

**report-download-modal**:
- **download-btn.n_clicks**:
    - read format from `format-dropdown`
    - read error-level from `error-level-dropdown`
    - call `odm_validation/tools/reportutils.write_<format>_report` with
      `report-content`
    - set `downloader.data` to the final formatted report data
    - reset report-download-modal-flag
