@startuml

!procedure $top_bar($has_datasets = 0)
    {*
        **Upload Dataset** | **Datasets** | **View Validation Profiles** | **Tutorials**
        **Datasets** |
        !if $has_datasets
            Ontario Lab.csv | Hamilton Lab.xlsx
        !else
            No Dataset Uploaded
        !endif
    }

        ...
        ...
        ...
        ...
!endprocedure

!procedure $sidebar($file_name, $show_validations)
{^"Sidebar"
    [Configure Dataset]
    [Validate Dataset]

    !if ($show_validations)
        {^"Previous Validations"

            {^"v2"
                [Validation 3]
            }

            {^"v1"
                [Validation 2]
                [Validation 1]
            }
        }
    !endif
}
!endprocedure

@enduml
