@startuml

!include ../screens.puml

(*) --> [User is in the **New Validation** dialog]"
{{
    $validation_setup_dialog()
}}
" as validation_setup_dialog

validation_setup_dialog --> [User clicks the **Customize Validation** \
button]"
{{
    $create_validation_profile_dialog()
}}
" as create_validation_profile_dialog

create_validation_profile_dialog --> [User clicks on the **Create Profile** \
button] validation_setup_dialog

create_validation_profile_dialog --> [User clicks on the **Cancel** button]\
validation_setup_dialog

@enduml
