@startuml

!include ../screens.puml

(*) --> [User is on the **Create Validation Profile** dialog]"
{{
    $create_validation_profile_dialog()
}}
" as create_validation_profile_dialog

create_validation_profile_dialog --> [User clicks on the **Upload Profile** \
button]"
{{
    $choose_validation_profile_dialog()
}}
" as choose_validation_profile_dialog

choose_validation_profile_dialog --> [User chooses a validation profile \
\n Update the create validation profile screen with the chosen profile] \
create_validation_profile_dialog

choose_validation_profile_dialog --> [User clicks on the **Close** button] \
create_validation_profile_dialog

@enduml
