@startuml

!include ../screens.puml

!procedure $upload_dataset_flow($start_screen, $start_message)
    (*) --> [$start_message]"
    {{
        %invoke_procedure($start_screen)
    }}
    " as start_screen

    start_screen --> [User clicks on the **Upload Dataset** button]"
    {{
        $choose_dataset_dialog()
    }}
    " as choose_dataset_dialog

    choose_dataset_dialog --> [User clicks on the **Cancel** button] start_screen

    choose_dataset_dialog --> [User chooses a CSV dataset by selecting a CSV \
file that hasn't been uploaded before and \n clicking the **Ok** button]"
    {{
        $configure_dataset_dialog("Ontario Lab.csv", 1)
    }}
    " as finish_csv_upload_dialog

    finish_csv_upload_dialog --> [User clicks on the **Close** button] start_screen

    finish_csv_upload_dialog --> [User clicks on the **Save** button]"
    {{
        $view_dataset_screen("Ontario Lab.csv", 0)
    }}
    " as view_dataset_screen

    choose_dataset_dialog --> [User chooses an Excel dataset by selecting an \
Excel file that hasn't been uploaded before and \n clicking the **Ok** button]"
    {{
        $configure_dataset_dialog("Hamilton Lab.xlsx", 0)
    }}
    " as finish_excel_upload_dialog

   finish_excel_upload_dialog --> [User clicks on the **Close** button] start_screen

   finish_excel_upload_dialog --> [User clicks on the **Save** button] view_dataset_screen

   choose_dataset_dialog -[#red]-> [User chooses a file that has the same name as an \
existing dataset]"
   {{
        $duplicate_dataset_dialog()
   }}
   " as duplicate_dataset_dialog

   duplicate_dataset_dialog -[#red]-> [User clicks on the **Update the Dataset** \
button] view_dataset_screen

    duplicate_dataset_dialog -[#red]-> [User clicks on the **Replace the Dataset** \
button]"
    {{
        $replace_dataset_confirm_dialog()
    }}
    " as replace_dataset_dialog_confirm

    replace_dataset_dialog_confirm -[#red]-> [User clicks on the **No** button]\
choose_dataset_dialog

    replace_dataset_dialog_confirm -[#red]-> [User clicks on the **Yes** \
button and \n they selected a CSV dataset] finish_csv_upload_dialog

     replace_dataset_dialog_confirm -[#red]-> [User clicks on the **Yes** \
button and \n they selected an Excel dataset] finish_excel_upload_dialog

!endprocedure

@enduml
