@startuml

!include ../screens.puml

(*) --> [User is on the **Validation Summary** screen]"
{{
    $validation_summary_page()
}}
" as validation_summary_page

validation_summary_page --> [User clicks on the **View Validation Report** \
button]"
{{
    $validation_report_dialog()
}}
" as validation_report_dialog

validation_report_dialog --> [User clicks on the **Close** button] \
validation_summary_page

@enduml
