@startuml

!procedure $top_bar($has_datasets = 0)
    {*
        **Upload Dataset** | **Datasets** | **View Validation Profiles** | **Tutorials** 
        **Datasets** | 
        !if $has_datasets 
            Ontario Lab.csv | Hamilton Lab.xlsx 
        !else
            No Dataset Uploaded
        !endif
    }

        ...
        ...
        ...
        ...
!endprocedure

!procedure $sidebar($file_name, $show_validations, $multiple_versions)
{^"Sidebar"
    [Configure Dataset] 
    [Validate Dataset]

    !if ($show_validations) && ($multiple_versions == 0)
        {^"Previous Validations"
            [Validation 1]
            [Validation 2]
        } 
    !endif 

    !if ($show_validations) && ($multiple_versions == 1)
        {^"Previous Validations"

            [v2 (Current) - validation 1]

            {^"v1" 
                [Validation 2]
                [Validation 3]
            }
        }
    !endif
}
!endprocedure

@enduml
