name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: python install/setup.py bdist_appimage
      - uses: softprops/action-gh-release@v2
        with:
          files: 'dist/*.AppImage'

  release-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: ./install/build_mac.sh
      - uses: softprops/action-gh-release@v2
        with:
          files: 'build/*.zip'

  release-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: python install/setup.py bdist_msi
      - uses: softprops/action-gh-release@v2
        with:
          files: 'dist/*.msi'
