name: Type Check

on: [pull_request]

jobs:
  type-check:
    runs-on: ubuntu-latest
    name: Type Check
    steps:
      - name: Check out source repository
        uses: actions/checkout@f43a0e5 # v3
      - name: Set up Python environment
        uses: actions/setup-python@7f4fc3e # v4
        with:
          python-version: "3.10"
      - name: Install Python Dependencies
        run: pip install -r requirements.txt
      - name: Type Check
        run: mypy
